insert into fun_fact VALUES
                         ('Cows can sleep standing up, but they can only dream lying down.'),
                         ('Just like you, cows have best friends. Not only does companionship make cows happier, it also makes them smarter.'),
                         ('Goats were one of the first animals to be tamed by humans and were being herded 9,000 years ago.'),
                         ('Goats can be taught their name and to come when called'),
                         ('Goats’ pupils (like many hooved animals) are rectangular. This gives them vision for 320 to 340 degrees (compared to humans with 160-210) around them without having to move and they are thought to have excellent night vision.'),
                         ('Pigs have the intelligence of a human toddler and are ranked as the fifth most intelligent animal in the world! In fact, pigs are more intelligent and trainable than any breed of dog.'),
                         ('Pigs are navigators: they can find their way home over large distances. They can often trot long distances and can reach up to 11 miles per hour running.'),
                         ('The average fully grown pig can weigh between 300 and 700 pounds. However the world record for the heaviest pig has not been beaten since 1933. Big Bill from Tennessee weighed in at 2,552 pounds. Now that is a big pig.'),
                         ('Pigs have amazing memories. They can remember things for years and years and can recognize and remember people and places, sources of food and even how to use objects.'),
                         ('Sheep are herbivores, which means their diet does not include meat. They typically eat seeds, grass and plants.'),
                         ('A group of sheep is known as a flock, herd, or mob.'),
                         ('The eyes of a sheep are placed on its head in such a way that they have a field of vision of around 300 degrees. This allows the sheep to see behind themselves – without having to turn their head!'),
                         ('If a sheep were to be put on its back, it would be unable to get back upright!'),
                         ('Chickens dream when they sleep! Just like humans and other mammals, chickens have a REM phase of sleep, which signifies dreaming.'),
                         ('Chickens can literally sleep with one eye open! Chickens have a sleep phase known as USWS (unihemispheric slow-wave sleep), where one half of the brain is lseeping while the other is awake.'),
                         ('Chickens have complex communication with many different meanings! Chickens are capable of at least 30 differet vocalizations and one means something specific. They alert each other for food, call young chicks, purr in contentment and warn other flock members of predators. Mother hens even talk to their babies while they are still in their eggs!'),
                         ('Chickens have a profound memory and are able to distinguish between more than 100 faces of their species. They can also recognise people.'),
                         ('Chickens are smart! The cognitive skills of chickens are similarly high to those of a dog or cat.'),
                         ('Chickens can taste salt but cannot perceive any sweet tastes.');
